DROP PROCEDURE spGetProjectsAndManagers
GO
DROP PROCEDURE spGetUserDetailsByUserName
GO
DROP PROCEDURE spGetPermissionsByRole
GO
DROP PROCEDURE spGetTasks
GO
DROP PROCEDURE spGetTask
GO
DROP PROCEDURE spGetUsersByProjectId
GO
DROP PROCEDURE spGetUsersWithRolesByProjectId