// <auto-generated />
namespace TaskBook.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Task));
        
        string IMigrationMetadata.Id
        {
            get { return "201407231526568_Task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
